# Generated by Django 3.0.7 on 2021-01-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechatgroupfile',
            old_name='id',
            new_name='file_id',
        ),
    ]
