# Generated by Django 3.0.7 on 2021-01-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0002_auto_20210115_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatgroupfile',
            name='called_name',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
