# Generated by Django 3.0.7 on 2021-01-18 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0003_wechatgroupfile_called_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('wx_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='微信号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '微信-群文件-用户信息',
                'verbose_name_plural': '微信-群文件-用户列表',
            },
        ),
        migrations.AlterModelOptions(
            name='wechatgroupfile',
            options={'verbose_name': '微信-群文件信息', 'verbose_name_plural': '微信-群文件列表'},
        ),
        migrations.RemoveField(
            model_name='wechatgroupfile',
            name='called_name',
        ),
        migrations.AddField(
            model_name='wechatgroupfile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechatgroupfile',
            name='remark',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='wechatgroupfile',
            name='file_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='wechatgroupfile',
            name='file_name',
            field=models.CharField(max_length=64, verbose_name='文件名'),
        ),
    ]
