# Generated by Django 3.0.7 on 2021-01-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0004_auto_20210118_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatFriendInfo',
            fields=[
                ('wx_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='微信号')),
                ('nickname', models.CharField(default='', max_length=64, verbose_name='昵称或备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '微信-好友信息',
                'verbose_name_plural': '微信-好友列表',
            },
        ),
        migrations.AddField(
            model_name='groupmember',
            name='nickname',
            field=models.CharField(default='', max_length=64, verbose_name='昵称或备注'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
