# Generated by Django 3.0.7 on 2021-01-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0005_auto_20210119_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatgroupfile',
            name='uploader',
            field=models.CharField(default='', max_length=64, verbose_name='上传者'),
        ),
    ]
