# Generated by Django 3.0.7 on 2021-01-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0006_wechatgroupfile_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatgroupfile',
            name='remark',
            field=models.CharField(default='', max_length=64, verbose_name='备注'),
        ),
    ]
