# Generated by Django 3.0.7 on 2021-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0007_auto_20210121_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatgroupfile',
            name='uploader_nickname',
            field=models.CharField(default='', max_length=64, verbose_name='上传者昵称'),
        ),
        migrations.AddField(
            model_name='wechatgroupfile',
            name='watch_times',
            field=models.IntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
