# Generated by Django 3.0.7 on 2021-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0008_auto_20210121_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('wx_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='微信号')),
                ('remark', models.CharField(default='', max_length=64, verbose_name='备注')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '微信文件管理-管理员',
                'verbose_name_plural': '微信文件管理-管理员列表',
            },
        ),
    ]
